apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service.yaml
  - deployment-blue.yaml
  - deployment-green.yaml
namespace: hello-gitops
images:
  - name: hello-gitops
    newName: carbonbasedsoul/hello-gitops
    newTag: 2cfd102ae4d8c186fab9aca091352da2bb5bdff7
